version: "3"

services:
  redis:
    image: ${IMAGE_REDIS}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${WORKSPACE}/db/data/redis:/data
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 50M
    command:
      ['redis-server', '/data/redis.conf']

  mysql:
    image: ${IMAGE_MYSQL}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ${WORKSPACE}/db/data/mysql/my.cnf:/etc/my.cnf
      - ${WORKSPACE}/db/data/mysql/data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 600M
