version: "3"

services:
  redis:
    image: ${IMAGE_REDIS}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${WORKSPACE}/db/data/redis:/data
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 50M
    command:
      ['redis-server', '/data/redis.conf']

  mysql:
    image: ${IMAGE_MYSQL}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ${WORKSPACE}/db/data/mysql/my.cnf:/etc/my.cnf
      - ${WORKSPACE}/db/data/mysql/data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 600M

  mongo:
    image: ${IMAGE_MONGO}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${WORKSPACE}/db/data/mongodb:/data/db
    deploy:
      resources:
        limits:
          memory: 500M

  dynamodb:
    image: ${IMAGE_DYNAMODB}
    environment:
      - ./Djava.library.path=./DynamoDBLocal_lib
    ports:
      - ${DYNAMO_PORT}:8000
    volumes:
      - ${WORKSPACE}/db/data/dynamodb:/home/dynamodblocal/data
    command:
      ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 50M
